#!/usr/bin/env python
from __future__ import print_function

import rospy

from sensor_msgs.msg import Image, CameraInfo
from qut_msgs.msg import Object

class CloudvisGGCNN(object):
  def __init__(self):
    self.service = rospy.Service('cloudvis/ggcnn', Object, self.request_cb)

    camera_info = rospy.wait_for_message(
      rospy.get_param('~camera/info_topic'), 
      CameraInfo
    )

    self.cam_K = np.array(camera_info.K).reshape((3, 3))

    self.base_frame = rospy.get_param('~camera/robot_base_frame')
    self.camera_frame = rospy.get_param('~camera/camera_frame')

    self.cam_fov = rospy.get_param('~camera/fov')
    
  def request_cb(self, request):

  def run(self):
    rospy.spin()

if __name__ == '__main__':
  rospy.init_node('cloudvis')

  cloudvis = Cloudvis()
  cloudvis.run()
